// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArZY6JBeVcZcrcBsFBnvAvDfwB6a4W_Ho',
    appId: '1:804513084873:web:352bad4390db28a08ee418',
    messagingSenderId: '804513084873',
    projectId: 'taskaty-one',
    authDomain: 'taskaty-one.firebaseapp.com',
    storageBucket: 'taskaty-one.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1AXiRFtcGgmzuozuMi_Nb3OpZblad29M',
    appId: '1:804513084873:android:dbba5933c2cb8e668ee418',
    messagingSenderId: '804513084873',
    projectId: 'taskaty-one',
    storageBucket: 'taskaty-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgxlnyfSCr7V1-ZnTVJJyNsXD0bit91pI',
    appId: '1:804513084873:ios:10200d21c39e7de58ee418',
    messagingSenderId: '804513084873',
    projectId: 'taskaty-one',
    storageBucket: 'taskaty-one.appspot.com',
    iosClientId: '804513084873-gi5g846plmnnl3mf1rel1m57leuropgt.apps.googleusercontent.com',
    iosBundleId: 'com.omarprogramzone.taskaty.taskaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgxlnyfSCr7V1-ZnTVJJyNsXD0bit91pI',
    appId: '1:804513084873:ios:a807bc9102c7c1fe8ee418',
    messagingSenderId: '804513084873',
    projectId: 'taskaty-one',
    storageBucket: 'taskaty-one.appspot.com',
    iosClientId: '804513084873-flnm90q89lmg7p2lup1snnr3agdu6hi6.apps.googleusercontent.com',
    iosBundleId: 'com.omarprogramzone.taskaty.taskaty.RunnerTests',
  );
}
